### ISSUE TITLE
Add nearest Irceline station and data to every sensor info block

### ISSUE THREAD

**Issue by Cinezaster** [CivicLabsBelgium/luftdaten_irceline_viewer#10]
Add nearest Irceline station with pm10 & pm2.5 to every sensor info block
![screen shot 2018-03-02 at 11 18 36](https://user-images.githubusercontent.com/188269/36894618-43c4fd9a-1e0c-11e8-9e2d-a79a22de5ac3.png)

**Comment by DavidSingh3** [comment]
feature added in 86847863debf83a759e8b1a0e379b4b5b65c3b13
