### ISSUE TITLE
Add a selector to show luftdaten current, current 1h mean, current24hour mean

### ISSUE THREAD

**Issue by Cinezaster** [CivicLabsBelgium/luftdaten_irceline_viewer#11]
### Luftdaten endpoints
* [http://api.luftdaten.info/static/v2/data.1h.json](http://api.luftdaten.info/static/v2/data.1h.json) - average of all measurements per sensor of the last hour
* [http://api.luftdaten.info/static/v2/data.24h.json](http://api.luftdaten.info/static/v2/data.24h.json) - average of all measurements per sensor of the 24 hours

**Comment by DavidSingh3** [comment]
support for luftdaten hourly and daily means added in e1140c5
