### ISSUE TITLE
Missing Irceline stations

### ISSUE THREAD

**Issue by lodagro** [CivicLabsBelgium/luftdaten_irceline_viewer#14]
Browsing in the code i see that an overview of Irceline stations is retrieved from
```
https://geo.irceline.be/sos/api/v1/stations?phenomenon=5
https://geo.irceline.be/sos/api/v1/stations?phenomenon=6001
```

The list of available stations is much longer than what is currently present on the map.
For example the stations in Beveren are not on the map, although these are in the above overview.

![Imgur Image](https://i.imgur.com/IFrvb9N.jpg)

**Comment by DavidSingh3** [comment]
As of 218939f5f8264e8926c7c0e3c4d4694d89f57c7e, all irceline stations should show up on the map.
